<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>用户登录</title>
</head>

<center>
<body>
    <h1><font color="blue">雪明的书店</font></h1>
    <form action="/login/login" method="post">
    <table>
        <tr><td>用户名:</td><td><input type="text" name="id"/></td></tr>
        <tr><td>用户密码:</td><td><input type="password" name="pwd"/></td></tr>
        <tr>
        <td><input type="submit" value="登录"/></td>
        <td><input type="reset" value="重新填写"/></td>
        </tr>
    </table>
    </form>
</body>
</center>

</html>
